var ABILITIES_ADV = [
    'Air Lock',
    'Armurbaston',
    'Brasier',
    'Chlorophylle',
    'Corps Sain',
    'Ciel Gris',
    'Crachin',
    'Sécheresse',
    'Torche',
    'Torche (activé)',
    'Météo',
    'Cran',
    'Coloforce',
    'Agitation',
    'Hyper Cutter',
    'Intimidation',
    'Lévitation',
    'Écaille Spéciale',
    'Engrais',
    'Force Pure',
    'Cuvette',
    'Sable Volant',
    'Voile Sable',
    'Coque Armure',
    'Anti-Bruit',
    'Essaim',
    'Glissade',
    'Isograisse',
    'Torrent',
    'Absorb Volt',
    'Absorb Eau',
    'Écran Fumée',
    'Garde Mystik'
];

var ABILITIES_DPP = ABILITIES_ADV.concat([
    'Adaptabilité',
    'Mauvais Rêve',
    'Télécharge',
    'Peau Sèche',
    'Filtre',
    'Don Floral',
    'Gloutonnerie',
    'Ignifuge',
    'Corps Gel',
    'Poing de Fer',
    'Maladresse',
    'Garde Magik',
    'Brise Moule',
    'Motorisé',
    'Normalise',
    'Soin Poison',
    'Téméraire',
    'Querelleur',
    'Simple',
    'Multi-Coups',
    'Début Calme',
    'Sniper',
    'Rideau Neige',
    'Alerte Neige',
    'Force Soleil',
    'Solide Roc',
    'Technicien',
    'Lentiteintée',
    'Inconscient'
]);

var ABILITIES_BW = ABILITIES_DPP.concat([
    'Analyste',
    'Contestation',
    'Défaitiste',
    'Acharné',
    'Rage Brûlure',
    'Infiltration',
    'Paratonnerre',
    'Multiécaille',
    'Envelocape',
    'Force Sable',
    'Baigne Sable',
    'Herbivore',
    'Sans Limite',
    'Lavabo',
    'Téra-Voltage',
    'Rage Poison',
    'TurboBrasier',
    'Tension'
]);

var ABILITIES_XY = ABILITIES_BW.concat([
    'Peau Céleste',
    'Aura Inversée',
    'Pare-Balles',
    'Aura Ténébreuse',
    'Souffle Delta',
    'Terre Finale',
    'Aura Féérique',
    'Toison Épaisse',
    'Méga Blaster',
    'Amour Filial',
    'Peau Féérique',
    'Mer Primaire',
    'Protéen',
    'Peau Gelée',
    'Prognathe',
    'Griffe Dure'
]);

var ABILITIES_SM = ABILITIES_XY.concat([
    'Créa-Herbe',
    'Créa-Brume',
    'Créa-Psy',
    'Créa-Élec',
    'Cruauté',
    'Filature',
    'Aquabulle',
    'Expert Acier',
    'Hydrata-Son',
    'Peau Électrique',
    'Boule de Poils',
    'Système Alpha',
    'Spectro-Bouclier',
    'Prisme-Armure',
    'Métallo-Garde',
    'Spectro-Bouclier', //aucune idée de pourquoi le talent est deux fois de suite ici : commentaire par Lokidari
    'Chasse-Neige',
    'Surf Caudal', 
    'Neuroforce',

]);

ABILITIES_XY.splice(ABILITIES_XY.indexOf('Paratonnerre'), 1, 'Paratonnerre');